### ISSUE TITLE
Reason for pip subprocess generation

### ISSUE THREAD

**Issue by yannikschaelte** [ICB-DCM/tumor2d#4]
Is there a reason for the lines https://github.com/ICB-DCM/tumor2d/blob/master/tumor2d/simulate.py#L63 generating a subprocess for the call to tumor2d_simulate? The package still seems to work directly calling `res = tumor2d_simulate(**kwargs)`, and removes a "daemons may not create subprocesses" error in pyABC.

@neuralyzer @drickert @ any developer? Thanks!

**Comment by yannikschaelte** [comment]
Ok, I think this will have been to avoid memory accumulating over time (is there some memory not correctly freed up?). On a test case, without the extra process, memory usage increased from 0.3% to 1.6% over 16 generations, while it stayed contact over time in the version as-is. Not ideal, but ok then.

**Comment by neuralyzer** [comment]
sorry for the late reply. as you already assumed, tumor2d has some memory leaks in its c++ implementation i was not able to find and fix. hence the subprocess thing.

**Comment by yannikschaelte** [comment]
Thanks for the reply! Yes, makes sense, then we'll just have to live with that.
